[package]
name = "cquill-migrate"
version = "0.0.1"
edition = "2021"

[profile.release]
lto = "fat"
opt-level = 3
strip = "symbols"

[lib]
name = "cquill"

[[bin]]
name = "cquill"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.7", features = ["derive"] }
lazy_static = "1.4.0"
regex = "1.7.1"
scylla = "0.7.0"
tokio = { version = "1.25.0", features = ["full"] }

[dev-dependencies]
rand = "0.8.5"
temp-dir = "0.1.11"
