[package]
name = "cquill-migrate"
version = "0.0.1"
edition = "2021"

[lib]
name = "cquill"

[[bin]]
name = "cquill"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.7", features = ["derive"] }
scylla = "0.7.0"
tokio = { version = "1.25.0", features = ["full"] }

[dev-dependencies]
temp-dir = "0.1.11"
