name: cquill CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      scylladb:
        image: scylladb/scylla
        ports:
          - 9042:9042
        options: >-
          --health-cmd "cqlsh -e 'describe cluster'"
          --health-start-period 30s
          --health-interval 2s
          --health-timeout 5s
          --health-retries 30
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release --all-features
      - run: cargo test
      - run: cargo clippy -- -D warnings
      - run: cargo fmt -v
      - run: git diff --exit-code
