name: cquill CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  verify:
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
      - fmt
    steps:
      - run: exit 0

  test:
    runs-on: ubuntu-latest
    services:
      scylladb:
        image: scylladb/scylla
        ports:
          - 9042:9042
        options: >-
          --health-cmd "cqlsh -e 'describe cluster'"
          --health-start-period 30s
          --health-interval 2s
          --health-timeout 5s
          --health-retries 30
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt -v
      - run: git diff --exit-code
