name: Cargo Update

on:
  schedule:
    - cron: '22 4 * * *'
  workflow_dispatch:

jobs:

  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2
      - run: cargo update
      - run: |
          set +e
          git diff --exit-code > /dev/null
          if [ "$?" -ne "0" ];
          then
            git config --global user.name "Adam McKee"
            git config --global user.email "adam.be.g84d@gmail.com"
            BRANCH_NAME=cargo-update-$(date +%y%m%d%H%M%S)
            git checkout -b $BRANCH_NAME
            git commit -am "cargo update"
            git push origin $BRANCH_NAME
            gh pr create --base main --title "cargo update $(date +%y-%m-%d)" --body "\`cargo update\` changes"
            gh pr merge --auto
          fi
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
